### ISSUE TITLE
ModuleNotFoundError: No module named 'node'

### ISSUE THREAD

**Issue by fazeelT** [wallarelvo/roshelper#2]
Trying rosrun on one node defined in python returns error:

rosrun package_name nodes/node_name

File "/python3.6/site-packages/roshelper/__init__.py", line 4, in <module>
    from node import Node
ModuleNotFoundError: No module named 'node'

import roshelper
  File "/python3.6/site-packages/roshelper/__init__.py", line 4, in <module>
    from node import Node
ImportError: cannot import name 'Node'

**Comment by fazeelT** [comment]
For me the directory ..../python/dist-packages/roshelper contained
__init__.py node.py partialnode.py ... __init__.py is trying to use node.py
which is in same directory. To solve this i replaced "from node import
Node" to "from roshelper.node import Node" in file __init__.py

I had same error with some other modules so i just added folder-name.* in
import statement that throw error.

Thanks

**Comment by a20r** [comment]
You shouldn't be running `rosrun package_name nodes/node_name`. Instead you should run `rosrun package_name node_name`. Also, roshelper is not tested with Python 3. Could you please try using Python 2 and let me know what is up?

**Comment by a20r** [comment]
Is this resolved?

**Comment by fazeelT** [comment]
Yes resolved
